sudo: required

language: R

services:
- docker

before_install:
- docker pull r-base

script:
- docker run --rm -v $(pwd):/app -w /app r-base bash -c "bin/setup"
- docker run --rm -v $(pwd):/app -w /app r-base bash -c "bin/test"
